GerenciamentoVendasProdutosClientes/Controllers/ClientesController.cs
using GerenciamentoVendasProdutosClientes.Models;
using GerenciamentoVendasProdutosClientes.Negocio;
using Microsoft.AspNetCore.Mvc;

namespace GerenciamentoVendasProdutosClientes.Controllers
{
    public class ClientesController : Controller
    {

        private readonly IClientesNegocio _clienteNegocio;

        public ClientesController(IClientesNegocio clienteNegocio)
        {
            _clienteNegocio = clienteNegocio;
        }
        public ActionResult Index(List<ClientesModel> clientes)
        {
          
            clientes = _clienteNegocio.BuscarTodos();

            return View(clientes);
        }  
        
        public ActionResult InserirCliente()
        {
            return View();
        }  
        
        public ActionResult EditarCliente(int id)
        {
            ClientesModel cliente = _clienteNegocio.ListarPorId(id);
            return View(cliente);
        }  
        
        public ActionResult ExcluirCliente(int id)
        {
            
            if (_clienteNegocio.ExcluirCliente(id))
            {
                TempData["Mensagem"] = "1";
            }
            else
            {
                TempData["Mensagem"] = "2";
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PesquisarCliente(string nome)
        {
            List<ClientesModel> clientePesquisa = new List<ClientesModel>();
            ClientesModel objCliente = new ClientesModel();



            List<ClientesModel> clientes = _clienteNegocio.BuscarTodos();

            var pesquisa = clientes.Where(cli => cli.nmCliente == nome).ToList();

            foreach (var cliente in pesquisa)
            {
                objCliente.Id = cliente.Id;
                objCliente.nmCliente = cliente.nmCliente;
                objCliente.cidade = cliente.cidade;


                clientePesquisa.Add(objCliente);
            }

            return View("Index",clientePesquisa);
        }

        [HttpPost]
        public ActionResult InserirCliente(ClientesModel cliente)
        {
            try
            {
                _clienteNegocio.InserirCliente(cliente);

                TempData["Mensagem"] = "3";
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                TempData["e"] = e.Message;

                return View(cliente);
            }
            
        }

        [HttpPost]
        public ActionResult EditarCliente(ClientesModel cliente)
        {
            try
            {
                _clienteNegocio.EditarCliente(cliente);

                TempData["Mensagem"] = "4";
                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                TempData["e"] = e.Message;

                return View(cliente);
            }
        }
    }
}

GerenciamentoVendasProdutosClientes/Controllers/ProdutosController.cs
using GerenciamentoVendasProdutosClientes.Models;
using GerenciamentoVendasProdutosClientes.Negocio;
using Microsoft.AspNetCore.Mvc;

namespace GerenciamentoVendasProdutosClientes.Controllers
{
    public class ProdutosController : Controller
    {

        private readonly IProdutosNegocio _produtoNegocio;

        public ProdutosController(IProdutosNegocio produtoNegocio)
        {
            _produtoNegocio = produtoNegocio;
        }
        public IActionResult Index(List<ProdutosModel> produtos)
        {
            produtos = _produtoNegocio.BuscarTodos();

            return View(produtos);

        } 
        
        public IActionResult InserirProduto()
        {
            return View();

        } 
        
        public IActionResult EditarProduto(int id)
        {
            ProdutosModel produto = _produtoNegocio.ListarPorId(id);

            return View(produto);

        } 
        
        public ActionResult ExcluirProduto(int id)
        {

            if (_produtoNegocio.ExcluirProduto(id))
            {
                TempData["Mensagem"] = "1";
            }
            else
            {
                TempData["Mensagem"] = "2";
            }

            return RedirectToAction("Index");
        }

        public ActionResult PesquisarProduto(string nome)
        {
            List<ProdutosModel> produtoPesquisa = new List<ProdutosModel>();
            ProdutosModel objProduto = new ProdutosModel();

            

            List<ProdutosModel> produtos = _produtoNegocio.BuscarTodos();

            var pesquisa = produtos.Where(prod => prod.dscProduto == nome).ToList();

            foreach (var produto in pesquisa)
            {
                objProduto.Id = produto.Id;
                objProduto.dscProduto = produto.dscProduto;
                objProduto.vlrUnitario = produto.vlrUnitario;


                produtoPesquisa.Add(objProduto);
            }

            return View("Index", produtoPesquisa);
        }

        [HttpPost]
        public IActionResult InserirVenda(ProdutosModel produto)
        {
            try
            {
                _produtoNegocio.InserirVenda(produto);

                TempData["Mensagem"] = "3";

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["e"] = e.Message;

                return View(produto);
            }
        }

        [HttpPost]
        public IActionResult EditarVenda(ProdutosModel produto)
        {
            try
            {
                _produtoNegocio.EditarVenda(produto);

                TempData["Mensagem"] = "4";

                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                TempData["e"] = e.Message;

                return View(produto);
            }
        }
    }
}

GerenciamentoVendasProdutosClientes/Controllers/VendasController.cs
using GerenciamentoVendasProdutosClientes.Models;
using GerenciamentoVendasProdutosClientes.Negocio;
using Microsoft.AspNetCore.Mvc;


namespace GerenciamentoVendasProdutosClientes.Controllers
{
    public class VendasController : Controller
    {

        private readonly IVendasNegocio _vendaNegocio;
        private readonly IClientesNegocio _clientesNegocio;
        private readonly IProdutosNegocio _produtosNegocio;

        public VendasController(IVendasNegocio vendaNegocio, IClientesNegocio clientesNegocio, IProdutosNegocio produtosNegocio)
        {
            _vendaNegocio = vendaNegocio;
            _clientesNegocio = clientesNegocio;
            _produtosNegocio = produtosNegocio;
        }
        public ActionResult Index()
        {
            List<VendasModel> vendas = _vendaNegocio.BuscarTodos();

            return View(vendas);
        }

        public ActionResult InserirVenda()
        {
            return View();
        }
        
        public IActionResult EditarVenda(int id)
        {

            VendasModel venda = _vendaNegocio.ListarPorId(id);

            return View(venda);
        }
        
        public ActionResult ExcluirVenda(int id)
        {
            if (_vendaNegocio.ExcluirVenda(id))
            {
                TempData["Mensagem"] = "1";
            }
            else
            {
                TempData["Mensagem"] = "2";
            }

            return RedirectToAction("Index");
        }

        public ActionResult PesquisarVenda(string nome)
        {
            List<VendasModel> vendaPesquisa = new List<VendasModel>();
            VendasModel objVenda = new VendasModel();

            List<VendasModel> vendas =_vendaNegocio.BuscarTodos();

            List<ClientesModel> clientes = _clientesNegocio.BuscarTodos();

            List<ProdutosModel> produtos = _produtosNegocio.BuscarTodos();

            var pesquisa = (from venda in vendas
                               join cliente in clientes
                               on venda.idCliente equals cliente.Id
                               join produto in produtos
                               on venda.idProduto equals produto.Id
                               where cliente.nmCliente == nome || produto.dscProduto == nome
                               select venda).ToList();

            vendas.Clear();

            foreach(var venda in pesquisa)
            {
                objVenda.Id = venda.Id;
                objVenda.idCliente = venda.idCliente;
                objVenda.idProduto = venda.idProduto;   
                objVenda.qtdVenda = venda.qtdVenda;
                objVenda.vlrUnitarioVenda = venda.vlrUnitarioVenda;
                objVenda.vlrTotalVenda = venda.vlrTotalVenda;
                objVenda.dthVenda = venda.dthVenda;

                vendas.Add(objVenda);
            }

            return View("Index", vendas);
        }

        [HttpPost]
        public ActionResult InserirVenda(VendasModel venda)
        {
            try
            {
                ProdutosModel produto = _produtosNegocio.ListarPorId(venda.idProduto);

                venda.vlrUnitarioVenda = produto.vlrUnitario;
                venda.vlrTotalVenda = (venda.qtdVenda * venda.vlrUnitarioVenda);

                _vendaNegocio.InserirVenda(venda);

                TempData["Mensagem"] = "3";

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["e"] = e.Message;

                return View(venda);
            }
        }

        [HttpPost]
        public ActionResult EditarVenda(VendasModel venda)
        {
            try
            {
                _vendaNegocio.EditarVenda(venda);

                TempData["Mensagem"] = "4";

                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                TempData["e"] = e.Message;

                return View(venda);
            }
        }
    }
}

GerenciamentoVendasProdutosClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head class="text-center">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento de Vendas, Produtos e Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GerenciamentoVendasProdutosClientes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 text-center">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vendas" asp-action="Index">Vendas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer" >
        <div class="container">
            &copy; 2022 - Gerenciamento de Vendas, Produtos e Clientes - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>